---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:update-workloads
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
  - "daemonsets"
  verbs:
  - "update"
  - "patch"
