---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  annotations: |
    rollout-on-change.kyverno.io/secret-dependencies: awx-app-credentials

  admin_user: admin
  admin_email: awx@example.com
  admin_password_secret: awx-admin-secret

  service_type: ClusterIP
  ingress_type: ingress
  ingress_annotations: |
    cert-manager.io/cluster-issuer: vault-issuer
  ingress_tls_secret: awx-tls-ingress
  hostname: awx.k8s.example.com
  ingress_path: /
  ingress_path_type: Prefix

  postgres_configuration_secret: awx-postgres-config
  secret_key_secret: awx-secret-key

  bundle_cacert_secret: awx-bundle-cacert

  projects_persistence: true
  projects_storage_class: truenas-nfs-csi
  projects_storage_size: 10Gi
  projects_storage_access_mode: ReadWriteMany
  redis_capabilities:
    - CHOWN
    - SETUID
    - SETGID
  security_context_settings:
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch

  # Potential fix for inventory sync failing
  # https://github.com/ansible/awx-operator/issues/1203
  ee_extra_env: |
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: disabled

  ee_images:
    - name: AWX EE (Pinned)
      # renovate: image=quay.io/ansible/awx-ee
      image: quay.io/ansible/awx-ee:24.6.1
    - name: AWX EE Custom
      image: harbor.k8s.example.com/local/awx-ee-custom:latest

  control_plane_ee_image: harbor.k8s.example.com/local/awx-ee-custom:latest

  init_container_image: quay.io/ansible/awx-ee
  # renovate: image=quay.io/ansible/awx-ee
  init_container_image_version: 24.6.1

  extra_settings:
    - setting: ALLOW_METRICS_FOR_ANONYMOUS_USERS
      value: "True"
    - setting: REMOTE_HOST_HEADERS
      value: "['HTTP_X_REAL_IP', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']"
