---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: awx-operator-controller-manager-metrics-monitor
  labels:
    control-plane: controller-manager
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: awx-web-monitor
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/part-of: awx
spec:
  jobLabel: app.kubernetes.io/component
  endpoints:
    - path: /api/v2/metrics/
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: awx
      app.kubernetes.io/part-of: awx
