---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_int/sign/k8s-example-com
    server: https://vault.k8s.example.com
    caBundleSecretRef:
      name: vault-k8s-bundle
      key: ca.crt
    auth:
      kubernetes:
        role: vault-issuer
        mountPath: /v1/auth/k8s/workload-prod
        serviceAccountRef:
          name: vault-issuer
          audiences:
            - https://kubernetes.default.svc.cluster.local
