---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-api-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: otel-api-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HYPERDX_API_KEY: "{{ .HYPERDX_API_KEY }}"

  dataFrom:
    - extract:
        key: kubernetes/workload-prod/clickstack
