---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
spec:
  template:
    metadata:
      labels:
        vector.dev/exclude: "true"
    spec:
      serviceAccountName: vector
      containers:
        - name: vector
          image: "docker.io/timberio/vector:latest-distroless-libc"
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: VECTOR_LOG
              value: "info"
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: api
              containerPort: 8686
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
            - name: var-log
              mountPath: /var/log/
              readOnly: true
            - name: var-lib-containers
              mountPath: /var/lib/containers
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: api
          readinessProbe:
            httpGet:
              path: /health
              port: api
      volumes:
        - name: config
          configMap:
            name: vector-agent-config
        - name: data
          hostPath:
            path: "/var/lib/vector"
            type: DirectoryOrCreate
        - name: var-log
          hostPath:
            path: /var/log/
        - name: var-lib-containers
          hostPath:
            path: /var/lib/containers/
