---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-autounseal-token
spec:
  mount: ""
  destination:
    create: true
    name: vso-autounseal-token
  path: auth/token/create-orphan
  params:
    policies: "autounseal"
    period: 24h
  refreshAfter: 24h
  renewalPercent: 67
  requestHTTPMethod: POST
  vaultAuthRef: vault-oci-auth
