---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        PAPERLESS_REDIS: 'redis://:{{ index . "valkey-password" }}@paperless-ngx-valkey:6379'

        PAPERLESS_DBENGINE: "postgresql"
        PAPERLESS_DBHOST: "paperless-ngx-cnpg-cluster-rw"
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: "paperless-ngx"
        PAPERLESS_DBUSER: '{{ index . "cnpg-username" }}'
        PAPERLESS_DBPASS: '{{ index . "cnpg-password" }}'

        PAPERLESS_SECRET_KEY: "{{ .secretKey }}"
        PAPERLESS_ADMIN_USER: "admin"
        PAPERLESS_ADMIN_PASSWORD: "{{ .adminPassword }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: secretkey-generator
      rewrite:
        - regexp:
            source: "(.*)"
            target: secretKey
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator
      rewrite:
        - regexp:
            source: "(.*)"
            target: adminPassword
    - extract:
        key: kubernetes/workload-prod/paperless-ngx-cnpg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cnpg-$1"
    - extract:
        key: kubernetes/workload-prod/paperless-ngx-valkey
      rewrite:
        - regexp:
            source: "(.*)"
            target: "valkey-$1"
