---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: harbor-admin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-s3-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: harbor-s3-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        REGISTRY_STORAGE_S3_ACCESSKEY: "{{ .accessKey }}"
        REGISTRY_STORAGE_S3_SECRETKEY: "{{ .secretKey }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: accesskey-generator
      rewrite:
        - regexp:
            source: "(.*)"
            target: accessKey
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: secretkey-generator
      rewrite:
        - regexp:
            source: "(.*)"
            target: secretKey
