---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cnpg-pushsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: "1m"
  secretStoreRefs:
    - name: hashicorp-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: cnpg-secret
  data:
    - match:
        remoteRef:
          remoteKey: kubernetes/%CLUSTER%/%APP%-cnpg
