---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-backup
spec:
  immediate: true
  schedule: "0 0 0 * * 0"
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
