---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: elastic
spec:
  version: 8.7.0
  kibanaRef:
    name: kibana
  fleetServerRef:
    name: fleet-server
  mode: fleet
  policyID: eck-agent
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        hostNetwork: true
        # 'hostPID: true' enables the Elastic Security integration to observe all process exec events on the host.
        # Sharing the host process ID namespace gives visibility of all processes running on the same host.
        hostPid: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
        containers:
          - name: agent
            resources:
              limits:
                cpu: 1
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 1Gi
            volumeMounts:
              - name: proc
                mountPath: /hostfs/proc
                readOnly: true
              - name: cgroup
                mountPath: /hostfs/sys/fs/cgroup
                readOnly: true
              - name: varlog
                mountPath: /var/log
                readOnly: true
              - name: etc-kubernetes
                mountPath: /hostfs/etc/kubernetes
                readOnly: true
              - name: var-lib
                mountPath: /hostfs/var/lib
                readOnly: true
              - name: passwd
                mountPath: /hostfs/etc/passwd
                readOnly: true
              - name: group
                mountPath: /hostfs/etc/group
                readOnly: true
              - name: etcsysmd
                mountPath: /hostfs/etc/systemd
                readOnly: true
              - name: etc-mid
                mountPath: /etc/machine-id
                readOnly: true
              - name: runlogjournal
                mountPath: /run/log/journal
                readOnly: true
        volumes:
          - name: proc
            hostPath:
              path: /proc
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
          - name: varlog
            hostPath:
              path: /var/log
          # Needed for cloudbeat
          - name: etc-kubernetes
            hostPath:
              path: /etc/kubernetes
          # Needed for cloudbeat
          - name: var-lib
            hostPath:
              path: /var/lib
          # Needed for cloudbeat
          - name: passwd
            hostPath:
              path: /etc/passwd
          # Needed for cloudbeat
          - name: group
            hostPath:
              path: /etc/group
          # Needed for cloudbeat
          - name: etcsysmd
            hostPath:
              path: /etc/systemd
          # Mount /etc/machine-id from the host to determine host ID
          # Needed for Elastic Security integration
          - name: etc-mid
            hostPath:
              path: /etc/machine-id
              type: File
          # Needed for journald input
          - name: runlogjournal
            hostPath:
              path: /run/log/journal
