---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-sa
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: argocd-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: argocd-sa
    namespace: kube-system
