---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: external-dns
spec:
  mount: internal
  type: kv-v2
  path: k8s/ops-prod/external-dns
  destination:
    create: true
    name: external-dns-secret
    transformation:
      templates:
        url:
          text: |
            {{- printf "TSIG_SECRET_KEY=%s" (get .Secrets "tsig-secret-key") -}}
            {{- printf "TSIG_SECRET_ALG=%s" (get .Secrets "tsig-secret-alg") -}}
            {{- printf "TSIG_KEY_NAME=%s" (get .Secrets "tsig-key-name") -}}
