---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  config:
    xpack:
      fleet:
        agents:
          elasticsearch:
            hosts:
              - https://elasticsearch-es-http.elastic.svc:9200
          fleet_server:
            hosts:
              - https://fleet-server-agent-http.elastic.svc:8220
        packages:
          - name: fleet_server
            version: latest
        agentPolicies:
          - name: Fleet Server on ECK policy
            id: fleet-server-eck
            namespace: default
            monitoring_enabled:
            - logs
            - metrics
            unenroll_timeout: 900
            is_default_fleet_server: true
            is_managed: true
            package_policies:
            - name: fleet_server-1
              id: fleet_server-1
              package:
                name: fleet_server
