---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-objectstore-connection
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: gitlab-objectstore-connection
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        connection: |
          provider: "AWS"
          region: "us-east-1"
          aws_access_key_id: "{{ .accessKey }}"
          aws_secret_access_key: "{{ .secretKey }}"
          aws_signature_version: "4"
          endpoint: "{{ .endpoint }}"
          path_style: "true"

  data:
    - secretKey: endpoint
      remoteRef:
        key: kubernetes/common/endpoints
        property: s3-endpoint

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: accesskey-generator
      rewrite:
        - regexp:
            source: "(.*)"
            target: accessKey
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: secretkey-generator
      rewrite:
        - regexp:
            source: "(.*)"
            target: secretKey

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-toolbox-objectstore
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: gitlab-toolbox-objectstore
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        config: |
          host_base: '{{ .endpoint | replace "https://" "" }}'
          host_bucket: '{{ .endpoint | replace "https://" "" }}'
          bucket_location: "{{ .region }}"
          use_https: "True"

          access_key: "{{ .aws_access_key_id }}"
          secret_key: "{{ .aws_secret_access_key }}"

  dataFrom:
    - extract:
        key: kubernetes/ops-prod/gitlab
        property: gitlab-objectstore-connection

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-ldap
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: gitlab-ldap
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        bind-password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-minio
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: gitlab-registry-minio
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        config: |
          s3:
            v4auth: "true"
            regionendpoint: "{{ .endpoint }}"
            pathstyle: "{{ .path_style }}"
            region: "{{ .region }}"
            bucket: "gitlab-registry"
            accesskey: "{{ .aws_access_key_id }}"
            secretkey: "{{ .aws_secret_access_key }}"

  dataFrom:
    - extract:
        key: kubernetes/ops-prod/gitlab
        property: gitlab-objectstore-connection

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-postgres-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: gitlab-postgres-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        postgresql-postgres-password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: kubernetes/ops-prod/gitlab-cnpg
        property: password
