---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gitlab-objectstore-connection
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 24h
  secretStoreRefs:
    - name: hashicorp-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: gitlab-objectstore-connection
  template:
    data:
      connection: "{{ .connection | fromYaml | toJson }}"
  data:
    - match:
        secretKey: connection
        remoteRef:
          remoteKey: kubernetes/ops-prod/gitlab
          property: gitlab-objectstore-connection

---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gitlab-ldap
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 24h
  secretStoreRefs:
    - name: hashicorp-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: gitlab-ldap
  template:
    data:
      bind-password: '{{ index . "bind-password" }}'
  data:
    - match:
        secretKey: bind-password
        remoteRef:
          remoteKey: kubernetes/ops-prod/gitlab
          property: bind-password
