---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-config-php
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: freshrss-config-php
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        config.custom.php: |
          <?php

          return [
                  # Set to `development` to get additional error messages,
                  #	or to `production` to get only the most important messages.
                  'environment' => 'production',

                  # Specify address of the FreshRSS instance,
                  # used when building absolute URLs, e.g. for WebSub.
                  # Examples:
                  # https://example.net/FreshRSS/p/
                  # https://freshrss.example.net/
                  'base_url' => 'https://freshrss.k8s.example.com',

                  # Natural language of the user interface, e.g. `en`, `fr`.
                  'language' => 'en',

                  # Name of the default user. Also used as the public user for anonymous reading.
                  'default_user' => 'admin',

                  # Allow or not the use of the API, used for mobile apps.
                  #	End-point is https://freshrss.example.net/api/greader.php
                  #	You need to set the user’s API password.
                  'api_enabled' => true,

                  'db' => [
                          # Type of database: `sqlite` or `mysql` or 'pgsql'
                          'type' => 'pgsql',

                          # Database server
                          'host' => 'freshrss-cnpg-cluster-rw',

                          # Database user
                          'user' => '"{{ .username }}"',

                          # Database password
                          'password' => '"{{ .password }}"',

                          # Database name
                          'base' => 'freshrss',
                  ]
          ];

  dataFrom:
    - extract:
        key: kubernetes/workload-prod/freshrss-cnpg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: freshrss-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        OIDC_PROVIDER_METADATA_URL: "{{ .OIDC_PROVIDER_METADATA_URL }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_CLIENT_CRYPTO_KEY: "{{ .OIDC_CLIENT_CRYPTO_KEY }}"
        OIDC_REMOTE_USER_CLAIM: "email"
        OIDC_SCOPES: "openid email"
  dataFrom:
    - extract:
        key: kubernetes/workload-prod/freshrss
