---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: valkey-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        password-file.conf: |
          requirepass "{{ .password }}"
          primaryauth "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: kubernetes/%CLUSTER%/%APP%-valkey
        property: password
