---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: valkey-pushsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  updatePolicy: IfNotExists
  deletionPolicy: Delete
  refreshInterval: "0"
  secretStoreRefs:
    - name: hashicorp-vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        remoteRef:
          remoteKey: kubernetes/%CLUSTER%/%APP%-valkey
