---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netbox-housekeeping
  labels:
    app.kubernetes.io/component: housekeeping
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 5
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: housekeeping
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: housekeeping
        spec:
          serviceAccountName: netbox
          automountServiceAccountToken: false
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: Always
          restartPolicy: OnFailure
          containers:
            - name: netbox-housekeeping
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
              image: ghcr.io/netbox-community/netbox:latest
              imagePullPolicy: IfNotPresent
              command:
                - /opt/netbox/venv/bin/python
                - /opt/netbox/netbox/manage.py
                - housekeeping
              envFrom:
                - configMapRef:
                    name: netbox-extra-config
                    optional: true
                - secretRef:
                    name: netbox-extra-secret
                    optional: true
              volumeMounts:
                - name: config
                  mountPath: /etc/netbox/config/configuration.py
                  subPath: configuration.py
                  readOnly: true
                - name: config
                  mountPath: /run/config/netbox
                  readOnly: true
                - name: secrets
                  mountPath: /run/secrets/netbox
                  readOnly: true
                - name: netbox-tmp
                  mountPath: /tmp
                - name: media
                  mountPath: /opt/netbox/netbox/media
                  subPath: ""
                  readOnly: false
          volumes:
            - name: config
              configMap:
                name: netbox-config
            - name: secrets
              secret:
                secretName: netbox-secret
            - name: netbox-tmp
              emptyDir:
                medium: Memory
            - name: media
              persistentVolumeClaim:
                claimName: netbox-media
                readOnly: false
