---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-proxy
spec:
  selector:
    matchLabels:
      name: metrics-proxy
  template:
    metadata:
      labels:
        name: metrics-proxy
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: metrics-proxy
        image: docker.io/haproxy:2.6.6
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 175Mi
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: metrics-proxy-config
