---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: %APP%-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: %APP%-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        key: "{{ .value }}"

  dataFrom:
    - extract:
        key: kubernetes/%CLUSTER%/%APP%
