---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: "admin"
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-keytab
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: keycloak-keytab
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        krb5.keytab: "{{ .keytab | b64dec }}"
  dataFrom:
    - extract:
        key: kubernetes/ops-prod/keycloak
