---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: keycloak-admin-pushsecret
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: "0"
  secretStoreRefs:
    - name: hashicorp-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: keycloak-admin-secret
  template:
    data:
      username: "{{ .username }}"
      password: "{{ .password }}"
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: kubernetes/ops-prod/keycloak
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: kubernetes/ops-prod/keycloak
          property: password
