---
apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - args:
    - sh
    image: docker.io/curlimages/curl
    name: curl
    stdin: true
    stdinOnce: true
    tty: true
  serviceAccountName: default
  hostNetwork: false
