---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  containers:
  - name: netshoot
    image: docker.io/nicolaka/netshoot
    command:
    - /bin/bash
    args:
    - -c
    - while true; do ping localhost; sleep 60; done
  serviceAccountName: default
  hostNetwork: false
