---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - args:
    - sh
    image: ubuntu:latest
    name: ubuntu
    stdin: true
    stdinOnce: true
    tty: true
  serviceAccountName: default
  hostNetwork: false
