---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-ce-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: renovate-ce-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        MEND_RNV_LICENSE_KEY: "{{ .MEND_RNV_LICENSE_KEY }}"
        MEND_RNV_GITLAB_PAT: "{{ .MEND_RNV_GITLAB_PAT }}"
        MEND_RNV_ADMIN_TOKEN: "{{ .MEND_RNV_ADMIN_TOKEN }}"
        MEND_RNV_SERVER_API_SECRET: "{{ .MEND_RNV_SERVER_API_SECRET }}"
        RENOVATE_TOKEN: "{{ .MEND_RNV_GITLAB_PAT }}"
        GITHUB_COM_TOKEN: "{{ .GITHUB_COM_TOKEN }}"
        DOCKER_REGISTRY_CONNECT_REDHAT_COM_USERNAME: "{{ .DOCKER_REGISTRY_CONNECT_REDHAT_COM_USERNAME }}"
        DOCKER_REGISTRY_CONNECT_REDHAT_COM_PASSWORD: "{{ .DOCKER_REGISTRY_CONNECT_REDHAT_COM_PASSWORD }}"
        RENOVATE_REDIS_URL: "redis://:{{ .valkey_password }}@renovate-ce-valkey:6379"
        PGUSER: "{{ .cnpg_username }}"
        PGPASSWORD: "{{ .cnpg_password }}"

  data:
    - secretKey: valkey_password
      remoteRef:
        key: kubernetes/ops-prod/renovate-ce-valkey
        property: password
        
  dataFrom:
    - extract:
        key: kubernetes/ops-prod/renovate-ce
    - extract:
        key: kubernetes/ops-prod/renovate-ce-cnpg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cnpg_$1"
