---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/k8s-example-com
    server: https://vault.k8s.example.com
    caBundleSecretRef:
      name: ca-bundle
      key: ca.crt
    auth:
      kubernetes:
        role: vault-issuer
        mountPath: /v1/auth/kube
        secretRef:
          name: vault-issuer-token
          key: token
