---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: netbox-pushsecret
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 24h
  secretStoreRefs:
    - name: hashicorp-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: netbox-secret
  template:
    data:
      email_password: "{{ .email_password }}"
      secret_key: "{{ .secret_key }}"
      superuser_password: "{{ .superuser_password }}"
      superuser_api_token: "{{ .superuser_api_token }}"
      db_password: "{{ .db_password }}"
      tasks_password: "{{ .tasks_password }}"
      cache_password: "{{ .cache_password }}"
      superuser_email: "{{ .superuser_email }}"
      superuser_username: "{{ .superuser_username }}"
  data:
    - match:
        secretKey: email_password
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: email_password
    - match:
        secretKey: secret_key
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: secret_key
    - match:
        secretKey: superuser_password
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: superuser_password
    - match:
        secretKey: superuser_api_token
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: superuser_api_token
    - match:
        secretKey: db_password
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: db_password
    - match:
        secretKey: tasks_password
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: tasks_password
    - match:
        secretKey: cache_password
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: cache_password
    - match:
        secretKey: superuser_email
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: superuser_email
    - match:
        secretKey: superuser_username
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: superuser_username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: netbox-extra-pushsecret
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 24h
  secretStoreRefs:
    - name: hashicorp-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: netbox-extra-secret
  template:
    data:
      AWS_S3_ACCESS_KEY_ID: "{{ .AWS_S3_ACCESS_KEY_ID }}"
      AWS_S3_SECRET_ACCESS_KEY: "{{ .AWS_S3_SECRET_ACCESS_KEY }}"
      AWS_S3_ENDPOINT_URL: "{{ .AWS_S3_ENDPOINT_URL }}"
  data:
    - match:
        secretKey: AWS_S3_ACCESS_KEY_ID
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: AWS_S3_ACCESS_KEY_ID
    - match:
        secretKey: AWS_S3_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: AWS_S3_SECRET_ACCESS_KEY
    - match:
        secretKey: AWS_S3_ENDPOINT_URL
        remoteRef:
          remoteKey: kubernetes/ops-prod/netbox
          property: AWS_S3_ENDPOINT_URL
