---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:35.115.0
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-secret
                    optional: false
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate
                  readOnly: true
                - name: cache
                  mountPath: /tmp/renovate
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
            - name: cache
              persistentVolumeClaim:
                claimName: renovate-cache
