# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: renovate-ce-db
# spec:
#   storageClassName: default
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-ce-cache
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
