---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  template:
    spec:
      containers:
        - name: thanos-query
          args:
            - query
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:9090
            - --log.level=info
            - --log.format=logfmt
            - --query.replica-label=prometheus_replica
            - --query.replica-label=rule_replica
            - --store=thanos-store.thanos.svc.cluster.local:10901
            - --store=kube-prometheus-kube-prome-thanos-discovery.monitoring.svc.cluster.local:10901
            - --store=thanos-query-tls.thanos.svc.cluster.local:10901
            - --store=thanos-sidecar-workload.k8s.example.com:10901
            - --query.auto-downsampling
