---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: uptime-agent
  namespace: elastic
spec:
  version: 8.7.0
  kibanaRef:
    name: kibana
  fleetServerRef:
    name: fleet-server
  mode: fleet
  policyID: uptime-agent
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
